name: PR Welcome Bot

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
    - 'main'

permissions:
  pull-requests: write

jobs:
  pr_bot:
    name: PR Bot
    runs-on: ubuntu-latest
    steps:
      - name: 'Add welcome comment on PR (draft)'
        uses: actions/github-script@v6
        if: "github.event.pull_request.draft"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.number }},
              body: 'Thank you for your contribution! 🙏 Let us know when you are ready for a review by publishing the PR.'
            });
      - name: 'Add welcome comment on PR'
        uses: actions/github-script@v6
        if: "!github.event.pull_request.draft"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.number }},
              body: 'Thank you for your contribution! 🙏 We will review your PR as soon as possible.\n\n\nWhile you are waiting, make sure to:\n\n\n- Add an entry in [our changelog](https://github.com/kedacore/keda/blob/main/CHANGELOG.md) in alphabetical order and link related issue\n- Update the [documentation](https://github.com/kedacore/keda-docs), if needed\n- Add unit & [e2e](https://github.com/kedacore/keda/blob/main/tests/README.md) tests for your changes\n- GitHub checks are passing\n- Is the DCO check failing? Here is [how you can fix DCO issues](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what)\n\n\nLearn more about:\n- Our [contribution guide](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md)'
            });
      - name: 'Apply review required label'
        uses: actions/github-script@v6
        if: "!github.event.pull_request.draft"
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["requires-pr-review"]
            })
